installer_checksums:
  Miniconda3-latest-Linux-x86_64.sh: 'bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2'
  Miniconda3-4.7.12.1-Linux-x86_64.sh: 'bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2'
  Anaconda3-2019.10-Linux-x86_64.sh: '46d762284d252e51cd58a8ca6c8adc9da2eadc82c342927b2f66ed011d1d8b53'
environments:
  - name: miniconda
    version: '4.7.12.1'
    miniconda: True
    python_version: 3
    installer_version: '4.7.12.1'
    condarc:
      channels:
        - defaults
  - name: anaconda
    version: '2020-02-tf1'
    miniconda: False
    python_version: 3
    installer_version: '2019.10'
    condarc:
      channels:
        - defaults
        - pytorch
        - gurobi
        - IBMDecisionOptimization
        - anaconda
        - mosek
        - conda-forge
    collections:
      - tensorflow-v1
      - triton-generic
  - name: anaconda
    version: '2020-02-tf2'
    miniconda: False
    python_version: 3
    installer_version: '2019.10'
    condarc:
      channels:
        - defaults
        - pytorch
        - gurobi
        - IBMDecisionOptimization
        - anaconda
        - mosek
        - conda-forge
    collections:
      - tensorflow-v2
      - triton-generic
collections:
  tensorflow-v1:
    conda_packages:
      - tensorboard
      - tensorflow=1.15.0
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  tensorflow-v2:
    conda_packages:
      - tensorboard
      - tensorflow=2.0.0
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  triton-generic:
    pip_packages:
      - bash-kernel
      - docopt
      - matlab-kernel
      - mne
      - numpy
      - pymanopt
      - pymvpa2
      - python-igraph
      - roboschool
      - sphinx
      - sphinx-rtd-theme
    conda_packages:
      - anaconda
      - anaconda-client
      - anaconda-navigator
      - anaconda-project
      - appdirs
      - asn1crypto
      - astropy
      - atomicwrites
      - backports
      - bcolz
      - bcrypt
      - beautifulsoup4
      - bitarray
      - bkcharts
      - blaze
      - bokeh
      - bottleneck
      - cffi
      - chardet
      - colorama
      - conda
      - conda-env
      - conda-tree
      - contextlib2
      - coverage
      - cplex
      - cryptography
      - cryptography-vectors
      - cuda100
      - cudatoolkit
      - cudnn
      - cython
      - dill
      - distributed
      - docutils
      - fastcache
      - fastparquet
      - gmpy2
      - gpy
      - gurobi
      - h5py
      - hdf4
      - hdf5
      - heapdict
      - html5lib
      - ipdb
      - ipykernel
      - ipyparallel
      - ipython
      - ipywidgets
      - joblib
      - jupyter
      - jupyterlab
      - jupyterlab_server
      - keras
      - keyring
      - llvmlite
      - lxml
      - markdown
      - matplotlib
      - metakernel
      - mkl
      - mkl-service
      - mkl_fft
      - mkl_random
      - mock
      - more-itertools
      - mosek
      - mpi4py
      - mpich2
      - navigator-updater
      - nbconvert
      - nccl
      - networkx
      - nitime
      - nltk
      - nose
      - numba
      - numexpr
      - numpydoc
      - olefile
      - openmp
      - pandas
      - pandoc
      - partd
      - pbr
      - pep8
      - phonopy
      - pillow
      - pip
      - pipdeptree
      - pixman
      - plotly
      - ply
      - prometheus_client
      - protobuf
      - pyarrow
      - pybind11
      - pycodestyle
      - pycrypto
      - pycurl
      - pydicom
      - pyflakes
      - pygments
      - pygpu
      - pylint
      - pympler
      - pyopenssl
      - pyparsing
      - pysocks
      - pytables
      - pytest
      - pytest-arraydiff
      - pytest-astropy
      - pytest-doctestplus
      - pytest-openfiles
      - pytest-remotedata
      - python
      - python-dateutil
      - python-snappy
      - pytorch
      - pytz
      - pyyaml
      - requests
      - scikit-image
      - scikit-learn
      - seaborn
      - setuptools
      - simplegeneric
      - singledispatch
      - six
      - sortedcollections
      - sphinxcontrib
      - spyder
      - sqlalchemy
      - sqlite
      - statsmodels
      - sympy
      - theano
      - thrift
      - torchvision
      - twisted
      - typing
      - unicodecsv
      - vtk
      - wheel
      - xgboost
      - xlrd
      - xlsxwriter
      - xlwt
